#!/bin/bash
cd /tmp
for d in `ls kile-live* -d 2>/dev/null`
        do
            if [ -d "$d" ]
            then
                echo "Folder is -> $d"
                cd $d
		mkdir -p template/diss
		cd /tmp
	    fi
            echo "Folders generated ... "
        done
